version: "3.9"
services:
  web-stg:
    image: ghcr.io/jaydensouthworth/portfolio:${IMAGE_TAG:-staging}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-stg.rule=Host(`in-dev.jaydensrealm.com`)
      - traefik.http.routers.portfolio-stg.entrypoints=websecure
      - traefik.http.routers.portfolio-stg.tls.certresolver=lehttp
      - traefik.http.services.portfolio-stg.loadbalancer.server.port=3000
    networks: [proxy]
networks:
  proxy:
    external: true
